force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Discontinued__c.field-meta.xml
<CustomField>
    <fullName>Discontinued__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Discontinued</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Frame_Material__c.field-meta.xml
<CustomField>
    <fullName>Frame_Material__c</fullName>
    <label>Frame Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frame_Material</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_on_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_on_Hand__c</fullName>
    <label>Quantity on Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{00000}</displayFormat>
        <label>Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Frame_Material__c.field-meta.xml
<CustomField>
    <fullName>Frame_Material__c</fullName>
    <label>Frame Material</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frame_Material</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Frame_Type__c.field-meta.xml
<CustomField>
    <fullName>Frame_Type__c</fullName>
    <label>Frame Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frame_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Pink</fullName>
    </customValue>
    <masterLabel>Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Frame_Material.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aluminum</fullName>
    </customValue>
    <customValue>
        <fullName>Carbon Fiber</fullName>
    </customValue>
    <customValue>
        <fullName>Titanium</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <masterLabel>Frame Material</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Frame_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BMX</fullName>
    </customValue>
    <customValue>
        <fullName>Mountain</fullName>
    </customValue>
    <customValue>
        <fullName>Cruisers</fullName>
    </customValue>
    <customValue>
        <fullName>Road</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>Performance</fullName>
    </customValue>
    <masterLabel>Frame Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OppBikesDataGenerator.cls
public class OppBikesDataGenerator {
    
    public static void start(){
        createOppProductsRecords();
        createInventoryRecords();
    }
    
    public static void createInventoryRecords(){
        List<Product__c> productList = new List<Product__c>();
        List<Inventory__c> invList = new List<Inventory__c>();

        productList = [SELECT id, Name, Frame_Material__c, Frame_Type__c, Color__c FROM Product__c];

        for(Product__c p: productList) {
            invList.add(inventoryTemplate(p, 'Green', 'S', 200, true));
            invList.add(inventoryTemplate(p, 'Black', 'M', 300, false));
            invList.add(inventoryTemplate(p, 'Blue', 'M', 300, false));
            invList.add(inventoryTemplate(p, 'Red', 'L', 350, false));
            invList.add(inventoryTemplate(p, 'Pink', 'XL', 400, false));
        }

        insert invList;
    }

    
    public static void createOppProductsRecords() {
        List<Product__c> productList = new List<Product__c>();
        String colors = 'Blue;Black;Green;Red;Pink';

        productList.add(productTemplate('Breeze', 'Aluminum', 'Cruisers', colors, 300));
        productList.add(productTemplate('Eagle', 'Carbon Fiber', 'Road', colors, 300));
        productList.add(productTemplate('Night Rider', 'Titanium', 'BMX', colors, 300));
        productList.add(productTemplate('Jet', 'Carbon Fiber', 'Performance', colors, 300));
        productList.add(productTemplate('Jet2', 'Carbon Fiber', 'Performance', colors, 350));
        productList.add(productTemplate('Jet3', 'Carbon Fiber', 'Performance', colors, 350));
        productList.add(productTemplate('Bluff', 'Aluminum', 'BMX', colors, 400));
        productList.add(productTemplate('Skylight', 'Aluminum', 'Hybrid', colors, 450));
        productList.add(productTemplate('Glacier', 'Aluminum', 'Hybrid', colors, 450));
        productList.add(productTemplate('Triton', 'Titanium', 'Road', colors, 500));
        productList.add(productTemplate('Triton2', 'Titanium', 'Road', colors, 500));
        productList.add(productTemplate('Radio', 'Aluminum', 'Cruisers', colors, 300));
        productList.add(productTemplate('Shadow', 'Aluminum', 'BMX', colors, 300));
        productList.add(productTemplate('Red Rock', 'Aluminum', 'Mountain', colors, 300));
        productList.add(productTemplate('Sky', 'Aluminum', 'Road', colors, 400));
        productList.add(productTemplate('Sky Max', 'Carbon Fiber', 'Hybrid', colors, 400));
        productList.add(productTemplate('Rocket', 'Carbon Fiber', 'Performance', colors, 600));
        productList.add(productTemplate('Rocket2', 'Carbon Fiber', 'Performance', colors, 650));
        productList.add(productTemplate('Stallion', 'Aluminum', 'Mountain', colors, 500));
        productList.add(productTemplate('Megatron', 'Titanium', 'Mountain', colors, 500));

        insert productList;
    }

    private static Product__c productTemplate(String name, String material, String type, String color, Integer price){
        Product__c p = new Product__c();
        p.Name = name;
        p.Frame_Material__c = material;
        p.Frame_Type__c = type;
        p.Color__c = color;
        p.Price__c = price;

        return p;
    }

    private static Inventory__c inventoryTemplate(Product__c p, String color, String size, Integer qty, boolean disc){
        Inventory__c inv = new Inventory__c();
            inv.Product_Name__c = p.Id;
            inv.Frame_Material__c = p.Frame_Material__c;
            inv.Frame_Type__c = p.Frame_Type__c;
            inv.Color__c = color;
            inv.Size__c = size;
            inv.Quantity_on_Hand__c = qty;
            inv.Discontinued__c = disc;

        return inv;
    }
}